# Generated by Django 5.2.7 on 2025-10-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the agent configuration.', max_length=100, unique=True, verbose_name='Agent Name')),
                ('parameters', models.JSONField(help_text='Configuration parameters for the agent.', verbose_name='Parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the configuration was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the configuration was last updated.', verbose_name='Updated At')),
                ('timings', models.JSONField(blank=True, help_text="Timing information related to the agent's operations.", null=True, verbose_name='Timings')),
            ],
        ),
        migrations.CreateModel(
            name='ChatInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the chat was created.', verbose_name='Chat Date')),
                ('message', models.TextField(help_text='The message sent.', verbose_name='Message')),
                ('is_agent_growth', models.BooleanField(default=False, help_text='Indicates if the message was sent by the agent growth system.', verbose_name='Is Agent Growth')),
                ('is_user', models.BooleanField(default=True, help_text='Indicates if the message was sent by the user.', verbose_name='Is User')),
                ('is_agent', models.BooleanField(default=False, help_text='Indicates if the message was sent by the agent.', verbose_name='Is Agent')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata related to the chat.', null=True, verbose_name='Metadata')),
                ('critical', models.BooleanField(default=False, help_text='Indicates if the chat is marked as critical.', verbose_name='Critical')),
                ('critical_type', models.CharField(blank=True, help_text='The type, if applicable.', max_length=100, null=True, verbose_name='Critical Type')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_start_time', models.DateTimeField(help_text='The start time of the summarized chat.', verbose_name='Summary Start Time')),
                ('summary_end_time', models.DateTimeField(help_text='The end time of the summarized chat.', verbose_name='Summary End Time')),
                ('summary_text', models.TextField(help_text='The summarized text of the chat.', verbose_name='Summary Text')),
                ('related_chats', models.ManyToManyField(blank=True, help_text='The chat information entries related to this summary.', related_name='summaries', to='agent.chatinformation', verbose_name='Related Chats')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the chat session started.', verbose_name='Started At')),
                ('current_state', models.JSONField(blank=True, help_text='The current state of the chat session.', null=True, verbose_name='Current State')),
                ('agent_configuration', models.ForeignKey(help_text='The agent configuration associated with this chat session.', on_delete=django.db.models.deletion.CASCADE, to='agent.agentconfiguration', verbose_name='Agent Configuration')),
                ('chat_infos', models.ManyToManyField(blank=True, help_text='The chat information entries in this session.', related_name='sessions', to='agent.chatinformation', verbose_name='Chat Informations')),
                ('summaries', models.ManyToManyField(blank=True, help_text='The chat summaries associated with this session.', related_name='sessions', to='agent.chatsummary', verbose_name='Chat Summaries')),
            ],
        ),
    ]
