# Generated by Django 5.2.7 on 2025-10-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='message_count',
            field=models.IntegerField(default=0, help_text='The number of messages in this session.', verbose_name='Message Count'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.TextField(blank=True, help_text='The current summary of the chat session.', null=True, verbose_name='Session Summary'),
        ),
    ]
