# Generated by Django 5.2.7 on 2025-10-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_chatsession_message_count_chatsession_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time of the last activity in this session.', verbose_name='Last Activity At'),
        ),
    ]
