# Generated by Django 5.2.7 on 2025-10-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_chatsession_last_activity_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='The date and time of the last activity in this session.', null=True, verbose_name='Last Activity At'),
        ),
    ]
