# Generated by Django 5.2.7 on 2025-10-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_chatsession_last_activity_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinformation',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates if the message has been read by the user (已读回执).', verbose_name='Is Read'),
        ),
    ]
