# Generated by Django 5.2.7 on 2025-11-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_chatinformation_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the agent (e.g., 'Alice', 'Bob').", max_length=100, verbose_name='Agent Name')),
                ('personality_prompt', models.TextField(help_text='The personality description for this agent.', verbose_name='Personality Prompt')),
                ('avatar_emoji', models.CharField(default='🤖', help_text='Emoji representing this agent.', max_length=10, verbose_name='Avatar Emoji')),
                ('color', models.CharField(default='#4A90E2', help_text='Color code for UI representation.', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this agent is currently active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this agent was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this agent was last updated.', verbose_name='Updated At')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chatinformation',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='The specific agent that sent this message (for multi-agent chats).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='agent.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='agents',
            field=models.ManyToManyField(blank=True, help_text='The agents participating in this chat session.', related_name='sessions', to='agent.agent', verbose_name='Active Agents'),
        ),
    ]
