# Generated by Django 5.2.8 on 2025-11-06 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_chatinformation_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who owns this agent.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who owns this session.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='name',
            field=models.CharField(help_text='The name of the agent configuration.', max_length=100, verbose_name='Agent Name'),
        ),
        migrations.AlterUniqueTogether(
            name='agentconfiguration',
            unique_together={('name', 'user')},
        ),
    ]
