# Generated by Django 5.2.7 on 2025-11-06 04:41

from django.db import migrations


def create_default_agents(apps, schema_editor):
    """Create default AI agents with different personalities"""
    Agent = apps.get_model('agent', 'Agent')
    
    default_agents = [
        {
            'name': 'Alice',
            'personality_prompt': 'You are Alice, a friendly and enthusiastic AI assistant. You love helping people and often use emojis. You explain things in a simple, conversational way and are always encouraging.',
            'avatar_emoji': '😊',
            'color': '#FF6B9D',
            'is_active': True,
        },
        {
            'name': 'Bob',
            'personality_prompt': 'You are Bob, a knowledgeable and professional AI expert. You provide detailed, technical explanations with precision. You are formal and focus on accuracy and best practices.',
            'avatar_emoji': '🧠',
            'color': '#4A90E2',
            'is_active': True,
        },
        {
            'name': 'Charlie',
            'personality_prompt': 'You are Charlie, a creative and playful AI assistant. You like to think outside the box and suggest innovative solutions. You use metaphors and analogies to explain complex concepts.',
            'avatar_emoji': '🎨',
            'color': '#FFA500',
            'is_active': True,
        },
    ]
    
    for agent_data in default_agents:
        Agent.objects.get_or_create(
            name=agent_data['name'],
            defaults={
                'personality_prompt': agent_data['personality_prompt'],
                'avatar_emoji': agent_data['avatar_emoji'],
                'color': agent_data['color'],
                'is_active': agent_data['is_active'],
            }
        )


def reverse_default_agents(apps, schema_editor):
    """Remove default agents"""
    Agent = apps.get_model('agent', 'Agent')
    Agent.objects.filter(name__in=['Alice', 'Bob', 'Charlie']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agent_chatinformation_agent_chatsession_agents'),
    ]

    operations = [
        migrations.RunPython(create_default_agents, reverse_default_agents),
    ]
